# Dependencies
highlighter:      true

#gems
gems:              [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            APastry
tagline:          'the notebook of all things edible'
description:      ''
url:              http://apastry.github.io

author:
  name:           'AP'
  url:            http://apastry.github.io

paginate:         5
excerpt_separator: <!--more-->

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/apastry/apastry.github.io
