# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            APastry
tagline:          'The Version Controlled Blog About Baking'
description:      ''
url:              http://apljungquist.github.io

author:
  name:           'AP'
  url:            http://apljungquist.github.io

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/apljungquist/apljungquist.github.io
